apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-pipeline-deployment
  labels:
    app: first-pipeline-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-pipeline-app
  template:
    metadata:
      labels:
        app: first-pipeline-app
    spec:
      containers:
      - name: first-pipeline-container
        image: nathirkasim/pipe:16
        ports:
        - containerPort: 8080 # Internal ONLY. Does not conflict with Jenkins.
