apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-pipeline-deployment
  labels:
    app: first-pipeline-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-pipeline-app
  template:
    metadata:
      labels:
        app: first-pipeline-app
    spec:
      containers:
      - name: first-pipeline-container
        image: nathirkasim/pipe:latest
        ports:
        - containerPort: 8080 # Internal ONLY. Does not conflict with Jenkins.
---
apiVersion: v1
kind: Service
metadata:
  name: first-pipeline-service
spec:
  type: NodePort 
  selector:
    app: first-pipeline-app
  ports:
    - port: 80
      targetPort: 8080 # Points to the container's internal 8080
      nodePort: 30007 # EXTERNAL ACCESS. We use 30007 to allow Jenkins to keep 8080.
