apiVersion: v1
kind: Service
metadata:
  name: first-pipeline-service
spec:
  type: NodePort 
  selector:
    app: first-pipeline-app
  ports:
    - port: 80
      targetPort: 8080 # Points to the container's internal 8080
      nodePort: 30007 # EXTERNAL ACCESS. We use 30007 to allow Jenkins to keep 8080.
